[package]
name = "aura-lex"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aura-luthor"
path = "src/luthor.rs"

[features]
default = []
parallel = ["rayon"]

[dependencies]
rayon = { version = "1.10.0", optional = true }
