use super::accepter::{self, ident, kw, LexemeState};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LexemeKind {
    KwVal,
    KwFn,
    KwType,
    KwTag,
    KwMain,
    KwMacro,
    KwImport,
    KwObject,
    IdentVal,
    IdentType,
    IdentTag,
    IdentMacro,
    IdentSubtype,
    OpDecl,
    OpEq,
    OpPlus,
    OpMinus,
    OpStar,
    OpSlash,
    OpCaret,
    OpUScore,
    OpPercent,
    OpAnd,
    OpAndAnd,
    OpOr,
    OpOrOr,
    OpNot,
    OpNotEq,
    OpEqEq,
    OpGt,
    OpGtEq,
    OpLt,
    OpLtEq,
    OpLtLt,
    OpGtGt,
    OpRArw,
    OpFatRArw,
    OpTilde,
    OpJoin,
    OpBSlash,
    OpRange,
    OpCRange,
    OpSpread,
    DelimOParen,
    DelimCParen,
    DelimOBrack,
    DelimCBrack,
    DelimOBrace,
    DelimCBrace,
    LitIntDec,
    LitIntBin,
    LitIntOct,
    LitIntHex,
    LitFlt,
    LitChr,
    LitStr,
    LitAtom,
    PtDot,
    PtComma,
    PtColon,
    PtSemi,
    Ws,
    CommentLine,
    CommentBlock,
}

impl From<LexemeState> for LexemeKind {
    fn from(value: LexemeState) -> Self {
        match value {
            LexemeState::Kw(kw_state) => match kw_state {
                kw::KwAccepter::Val(_) => Self::KwVal,
                kw::KwAccepter::Fn(_) => Self::KwFn,
                kw::KwAccepter::Type(_) => Self::KwType,
                kw::KwAccepter::Tag(_) => Self::KwTag,
                kw::KwAccepter::Main(_) => Self::KwMain,
                kw::KwAccepter::Macro(_) => Self::KwMacro,
                kw::KwAccepter::Import(_) => Self::KwImport,
                kw::KwAccepter::Object(_) => Self::KwObject,
            },
            LexemeState::Ident(ident_state) => match ident_state {
                ident::IdentAccepter::Val(_) => Self::IdentVal,
                ident::IdentAccepter::Type(_) => Self::IdentType,
                ident::IdentAccepter::Tag(_) => Self::IdentTag,
                ident::IdentAccepter::Macro(_) => Self::IdentMacro,
                ident::IdentAccepter::Subtype(_) => Self::IdentSubtype,
            },
            LexemeState::Op(op_state) => match op_state {
                accepter::op::OpAccepter::Decl(_) => Self::OpDecl,
                accepter::op::OpAccepter::Eq(_) => Self::OpEq,
                accepter::op::OpAccepter::Plus(_) => Self::OpPlus,
                accepter::op::OpAccepter::Minus(_) => Self::OpMinus,
                accepter::op::OpAccepter::Star(_) => Self::OpStar,
                accepter::op::OpAccepter::Slash(_) => Self::OpSlash,
                accepter::op::OpAccepter::Caret(_) => Self::OpCaret,
                accepter::op::OpAccepter::UScore(_) => Self::OpUScore,
                accepter::op::OpAccepter::Percent(_) => Self::OpPercent,
                accepter::op::OpAccepter::And(_) => Self::OpAnd,
                accepter::op::OpAccepter::AndAnd(_) => Self::OpAndAnd,
                accepter::op::OpAccepter::Or(_) => Self::OpOr,
                accepter::op::OpAccepter::OrOr(_) => Self::OpOrOr,
                accepter::op::OpAccepter::Not(_) => Self::OpNot,
                accepter::op::OpAccepter::NotEq(_) => Self::OpNotEq,
                accepter::op::OpAccepter::EqEq(_) => Self::OpEqEq,
                accepter::op::OpAccepter::Gt(_) => Self::OpGt,
                accepter::op::OpAccepter::GtEq(_) => Self::OpGtEq,
                accepter::op::OpAccepter::Lt(_) => Self::OpLt,
                accepter::op::OpAccepter::LtEq(_) => Self::OpLtEq,
                accepter::op::OpAccepter::LtLt(_) => Self::OpLtLt,
                accepter::op::OpAccepter::GtGt(_) => Self::OpGtGt,
                accepter::op::OpAccepter::RArw(_) => Self::OpRArw,
                accepter::op::OpAccepter::FatRArw(_) => Self::OpFatRArw,
                accepter::op::OpAccepter::Tilde(_) => Self::OpTilde,
                accepter::op::OpAccepter::Join(_) => Self::OpJoin,
                accepter::op::OpAccepter::BSlash(_) => Self::OpBSlash,
                accepter::op::OpAccepter::Range(_) => Self::OpRange,
                accepter::op::OpAccepter::CRange(_) => Self::OpCRange,
                accepter::op::OpAccepter::Spread(_) => Self::OpSpread,
            },
            LexemeState::Delim(delim_state) => match delim_state {
                accepter::delim::DelimAccepter::OParen(_) => Self::DelimOParen,
                accepter::delim::DelimAccepter::CParen(_) => Self::DelimCParen,
                accepter::delim::DelimAccepter::OBrack(_) => Self::DelimOBrack,
                accepter::delim::DelimAccepter::CBrack(_) => Self::DelimCBrack,
                accepter::delim::DelimAccepter::OBrace(_) => Self::DelimOBrace,
                accepter::delim::DelimAccepter::CBrace(_) => Self::DelimCBrace,
            },
            LexemeState::Lit(lit_state) => match lit_state {
                accepter::lit::LitAccepter::IntDec(_) => Self::LitIntDec,
                accepter::lit::LitAccepter::IntBin(_) => Self::LitIntBin,
                accepter::lit::LitAccepter::IntOct(_) => Self::LitIntOct,
                accepter::lit::LitAccepter::IntHex(_) => Self::LitIntHex,
                accepter::lit::LitAccepter::Flt(_) => Self::LitFlt,
                accepter::lit::LitAccepter::Chr(_) => Self::LitChr,
                accepter::lit::LitAccepter::Str(_) => Self::LitStr,
                accepter::lit::LitAccepter::Atom(_) => Self::LitAtom,
            },
            LexemeState::Pt(pt_state) => match pt_state {
                accepter::pt::PtState::Dot(_) => Self::PtDot,
                accepter::pt::PtState::Comma(_) => Self::PtComma,
                accepter::pt::PtState::Colon(_) => Self::PtColon,
                accepter::pt::PtState::Semi(_) => Self::PtSemi,
            },
            LexemeState::Ws(_) => Self::Ws,
            LexemeState::Comment(comment_state) => match comment_state {
                accepter::comment::CommentAccepter::Line(_) => Self::CommentLine,
                accepter::comment::CommentAccepter::Block(_) => Self::CommentBlock,
            },
        }
    }
}